# Coding Quiz for L13-14 (23 July 2022)

Please complete the following notebook and submit your answers using the following link:

https://forms.gle/PTQa79kNH1DgBz2w8

There are a total of **5** questions and you have **15 mins** for this quiz. Good luck! 

In [29]:
import numpy as np
import pandas as pd
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [30]:
df = pd.DataFrame(sb.load_dataset('exercise'), index=None)

In [31]:
df.head()

Unnamed: 0  id     diet  pulse    time  kind
0           0   1  low fat     85   1 min  rest
1           1   1  low fat     85  15 min  rest
2           2   1  low fat     88  30 min  rest
3           3   2  low fat     90   1 min  rest
4           4   2  low fat     92  15 min  rest

## Data Pre-processing & Analysis

In [32]:
# remove the first two columns

 # your code here (1)
df.drop(df.columns[0:2], axis=1, inplace=True)
df

diet  pulse    time     kind
0   low fat     85   1 min     rest
1   low fat     85  15 min     rest
2   low fat     88  30 min     rest
3   low fat     90   1 min     rest
4   low fat     92  15 min     rest
..      ...    ...     ...      ...
85   no fat    135  15 min  running
86   no fat    130  30 min  running
87   no fat     99   1 min  running
88   no fat    111  15 min  running
89   no fat    150  30 min  running

[90 rows x 4 columns]

**Q1: Which column(s) contain(s) categorical data?**

In [33]:
 # your code here (2)

In [42]:
# put the column name of categorical features in cat list and numerical features in num list
# DO NOT put "kind" in either list

cat = ["diet", "time"] # your code here (3)
num = ["pulse"] # your code here (4)
cat

['diet', 'time']

**Q2: What is the average pulse for people that are at rest, walking and running respectively? (round to nearest integer)**

In [43]:
df.kind.value_counts()

rest       30
walking    30
running    30
Name: kind, dtype: int64

In [44]:
# Calculate average pulse for people that are at rest, walking and running respectively

# your code here (5)

df.groupby("kind")["pulse"].mean().round(0)

kind
rest        91.0
walking     95.0
running    113.0
Name: pulse, dtype: float64

*Hint: use groupby() and mean()*

## One-hot encoding & feature scaling

In [45]:
# one-hot encoding on categorical features

cat_encoded = OneHotEncoder().fit_transform(df[cat]).toarray()


In [46]:
# scaling on numerical features

num_scaled = StandardScaler().fit_transform(df[num])
num_scaled

array([[-0.99487718],
       [-0.99487718],
       [-0.79184102],
       [-0.65648358],
       [-0.52112614],
       [-0.45344742],
       [-0.18273254],
       [-0.18273254],
       [-0.3857687 ],
       [-1.33327078],
       [-1.19791334],
       [-1.13023462],
       [-0.58880486],
       [-0.52112614],
       [-0.58880486],
       [-1.13023462],
       [-1.13023462],
       [-1.0625559 ],
       [-0.85951974],
       [-0.79184102],
       [-0.65648358],
       [-0.52112614],
       [-0.3857687 ],
       [-0.31808998],
       [-0.18273254],
       [-0.0473751 ],
       [-0.25041126],
       [ 0.02030362],
       [-0.18273254],
       [ 0.02030362],
       [-0.92719846],
       [-0.92719846],
       [-1.0625559 ],
       [-0.45344742],
       [ 0.22333977],
       [ 0.29101849],
       [-0.65648358],
       [-0.52112614],
       [-0.45344742],
       [-0.31808998],
       [-0.25041126],
       [ 0.02030362],
       [-0.7241623 ],
       [-0.25041126],
       [-0.31808998],
       [-1

In [48]:
# combine the numpy arrays cat_encoded and num_scaled as input features

X = np.concatenate([cat_encoded, num_scaled], axis=1) # your code here (6)

In [57]:
X.shape

(90, 6)

*Hint: Try np.concatenate()* 

*https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html*

**Q3: How many rows and columns are there in X?**

In [ ]:
 # your code here (7)

In [49]:
Y = df.kind.to_numpy() # prediction label

## Model Training & Evaluation

In [50]:
# Split the data into training and testing set with a ratio of 8:2 and random state 10

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=10)

In [61]:
pd.DataFrame(predict)

0
0   running
1      rest
2      rest
3   running
4      rest
5      rest
6      rest
7   walking
8      rest
9      rest
10  walking
11  running
12  running
13  running
14  running
15  walking
16  walking
17     rest

In [51]:
# Fit a logistic regression model

model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [52]:
# Prediction on the test set

predict = model.predict(x_test)
print("Accuracy: {}".format(accuracy_score(y_test, predict)))

Accuracy: 0.6111111111111112


**Q4: Based on precision score, the model performed best on which kind of exercise (rest/walking/running)?**

In [54]:
# calculate the precision of the model

 # your code here (8)
precision_score(y_test, predict, average=None)

array([0.625     , 0.66666667, 0.5       ])

*Hint: Try precision_score()* 

*Hint 2: Remember to set average=None to return the scores for each class*

*https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html*

**Q5: Based on recall score, the model performed best on which kind of exercise (rest/walking/running)?**

In [55]:
# calculate the recall of the model

 # your code here (9)
recall_score(y_test, predict, average=None)

array([1.        , 0.66666667, 0.28571429])

*Hint: Try recall_score()* 

*Hint 2: Remember to set average=None to return the scores for each class*

*https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html*

## End of Quiz! 👏
## Remember to submit your answers and notebook!